global:
  imageRegistry: "registry.gitlab.com/yourrepo"
  replicaCount: 3

mazeServer:
  image: "maze-server:v1.2.0"
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  service:
    type: ClusterIP
    port: 8000
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: maze.yourdomain.com
        paths:
          - path: /
            pathType: Prefix

game2048:
  image: "2048-server:v1.5.0"
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
  service:
    type: ClusterIP
    port: 3000

redis:
  enabled: true
  architecture: "replication"
  auth:
    enabled: true
    password: "your-redis-password"
  master:
    persistence:
      enabled: true
      size: 10Gi
  replica:
    replicaCount: 2
    persistence:
      enabled: true
      size: 10Gi

monitoring:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  grafana:
    enabled: true
    adminPassword: "your-grafana-password"
    dashboards:
      enabled: true
      label: grafana_dashboard

istio:
  enabled: true
  gateway:
    enabled: true
    hosts:
      - "*.yourdomain.com"
  virtualService:
    enabled: true
    hosts:
      - maze.yourdomain.com
      - 2048.yourdomain.com 